language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.11"

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.8"
    - node_js: "0.11"

script: false

deploy:
  on:
    tags: true
  provider: npm
  email: "aa1ronham@gmail.com"
  api_key:
    - secure: "FxPyl49eQDLjJvd+yRd1KzN6SMLNWSA+Hpw6y6BvvzqOBhjMTNKNA061odMCM7i2kJE5UgyJly35yS1awCY1NuUYvPsJ01FkIjPDq+mipx5wUgArTU6fH56tlmtJitvLEBIQxgbf2XHOeberQ+zPL0Nh0Zy8Wgxjjg93fVRoH/E="

after_script:
  - "git describe --tags --exact-match 2>/dev/null"
  - "echo $?"

notifications:
  email:
    on_success: "always"
